language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false 
node_js:
  - '10'
  - '11'
  - '12'
script:
  - npm run test

jobs:
  include:
    - stage: deploy_docs
      before_script:
        - npm run build:docs
      node_js:
        - '12'
      script: if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run deploy-docs; fi
    - stage: npm_release
      before_script:
        - npm run build:prod
      node_js:
        - '12'
      script: if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run semantic-release; fi
      after_success:
        - npm run report-coverage
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
