language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '11'
  - '12'
script:
  - npm run test

jobs:
  include:
    - stage: Production
      before_script:
        - npm run build:docs
      node_js:
        - '12'
      name: deploy_api_reference
      if: branch = master
      env: TRAVIS_PULL_REQUEST = false
      script: yarn deploy-docs
    - name: deploy_docs
      before_script:
        - npm run build:docusaurus
      node_js:
        - '12'
      if: branch = master
      env: TRAVIS_PULL_REQUEST = false
      script: npm run deploy-docusaurus
    - name: npm_release
      node_js:
        - '12'
      before_script:
        - npm run build
      if: branch = master OR branch = next
      env: TRAVIS_PULL_REQUEST = false
      script: yarn semantic-release
    - name: produce_coverage
      node_js:
        - '12'
      before_script:
        - npm run test:cov
      script: if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run report-coverage; fi
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
