name: Mark stale issues and pull requests

on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 30
          stale-issue-message: 'Marking this issue as stale as there has been no activity in the last 30 days'
          stale-pr-message: 'Marking this PR as stale as there has been no activity in the last 30 days'
          stale-issue-label: 'no-issue-activity'
          stale-pr-label: 'no-pr-activity'
          close-issue-message: 'Closing this issue since it was marked as stale and there has been no activity in the last 7 days'
          close-pr-message: 'Closing this PR since it was marked as stale and there has been no activity in the last 7 days'
          exempt-issue-labels: 'enhancement,bug'
